baseURL = 'https://veprogames.github.io'
languageCode = 'en-us'
title = 'VeproGames'
theme = "vepronix"
rssLimit = 25

[menu]
    [[menu.main]]
        name = "RSS"
        identifier = "rss"
        url = "/index.xml"
        weight = 100
    [[menu.footer]]
        name = "CC-BY-ND 4.0"
        identifier = "license"
        url = "/LICENSE"
        weight = 10